
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /App

RUN dotnet workload install aspire

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /App
COPY --from=build /App/out .
ENTRYPOINT ["dotnet", "BlazorApp.ApiService.dll"]
